<!DOCTYPE html>

<head>
    <link rel="stylesheet" type="text/css" href="stylesheet.css"?
    <meta charset=utf-8>

    <title>Post And Rail Calculator</title>
</head>

<main>
    <p>
        Please enter AT LEAST your number of rails OR your fence length.
    </p>
    <form method="post" action="fenceprocessing.php">
        <input type="number" name="posts" min="2" style="width:240px" placeholder="please enter a valid integer over 2..."></br></br>
        <input type="number" name="rails    " min="1" style="width:240px" placeholder="please enter a valid integer"></br></br>
        <input type="number" name="fencelength" min="1" style="width:240px" placeholder="please enter a valid integer"><label>Meters</label></br></br>
        <input type="submit" value="Submit" id="submit-button"></br>
    </form>
</main>